namespace AinSoph.Items;

public enum ItemType
{
    Primitive,  // Exists at world start — ground, sky, manna
    Natural,    // Generated by world rules — trees, mushrooms, animals
    Crafted     // Created by a PC or NPC, passed through the Council
}

/// <summary>
/// An item is anything physical in the world that is not a PC or NPC.
/// The ground is an item. A tree is an item. A piece of manna is an item.
/// </summary>
public class Item
{
    public string Id { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public ItemType Type { get; set; }
    public string CreatedBy { get; set; } = string.Empty; // entity id, empty for primitives

    /// <summary>Whether consuming this item satisfies the daily eat requirement.</summary>
    public bool Edible { get; set; }

    /// <summary>Lifespan in real hours. Null = does not decay. Manna = 24.</summary>
    public float? LifespanHours { get; set; }

    public bool Fixed { get; set; } // true = cannot be moved (ground, sky)

    public Dictionary<string, object> Properties { get; set; } = new();
}

/// <summary>The primitive items that exist at world start.</summary>
public static class PrimitiveItems
{
    public const string Ground = "primitive.ground";
    public const string Sky    = "primitive.sky";
    public const string Manna  = "primitive.manna";
}
